import type { Metadata } from "next";
import { Comfortaa } from "next/font/google";
import "./globals.css";
import { Header } from "@/components/blocks/Header";
import { Footer } from "@/components/blocks/Footer";
import { ReduxProvider } from "@/lib/ReduxProvider";
import { InitialRender } from "@/components/helper/InitialRender";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const comfortaa = Comfortaa({
  subsets: ["latin"],
  weight: ["400", "700"],
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${comfortaa.className} antialiased container mx-auto px-4`}
      >
        <ReduxProvider>
          <InitialRender />
          <Header />
          {children}
          <Footer />
        </ReduxProvider>
      </body>
    </html>
  );
}
